name: nextjs-build-check

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

# TODO later: test coverage check
jobs:
  build:
    name: Setup, Build, Lint, Commits, Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.12.x
          cache: "npm"  # local act does not work here
      
      - name: Install
        run: npm ci
      
      - name: Build
        run: npm run build
    
      - name: ESLint
        run: npm run lint
      
      - name: Conventional commits
        uses: webiny/action-conventional-commits@v1.1.0

      - name: Test
        run: npm test

    