name: nextjs-deploy-prod-cloud-run

on: workflow_dispatch

jobs:
  deploy:
    uses: ./.github/workflows/deploy-common.yaml
    with:
      environment: production
      cloudrun-service: cflabs-web-prod
      cloudrun-region: us-west1
      artifact-repo-build-prefix: build-prod-
      artifact-repo-name: us-west1-docker.pkg.dev/zkpool-web/zkpool-web/cflabs-web-prod
    secrets: inherit
