name: nextjs-deploy-cloud-run

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      cloudrun-service:
        required: true
        type: string
      cloudrun-region:
        required: true
        type: string
      artifact-repo-build-prefix:
        required: true
        type: string
      artifact-repo-name:
        required: true
        type: string

jobs:
  deploy:
    name: Setup, build and deploy to ${{ inputs.environment }}
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - id: auth
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v1"
        with:
          token_format: access_token
          workload_identity_provider: ${{ secrets.GOOGLE_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
          access_token_lifetime: 300s

      - name: Login to Artifact Registry
        uses: docker/login-action@v1
        with:
          registry: us-west1-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ inputs.artifact-repo-name }}
          tags: |
            type=sha,prefix=${{ inputs.artifact-repo-build-prefix }},format=short
            type=raw,value=latest

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          cache-from: type=gha
          cache-to: type=gha
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            "ENV=${{ inputs.environment }}"
          secrets: |
            "web3auth_client_id=${{ secrets.WEB3AUTH_CLIENT_ID }}"

      - name: "Deploy CFLabs web to ${{ inputs.environment }}"
        uses: "google-github-actions/deploy-cloudrun@v1"
        with:
          service: ${{ inputs.cloudrun-service }}
          region: ${{ inputs.cloudrun-region }}
          image: ${{ fromJSON(steps.meta.outputs.json).tags[1] }}
